#!/bin/bash

DOCKER_IMAGE=marcoieni/doc-org

# download or update image
docker pull $DOCKER_IMAGE

DEST="/root/project"

if [ -z "$1" ]
then
    SOURCE=$(pwd)
else
    SOURCE=$1
fi

MOUNT_ARG="type=volume,source="$SOURCE",dst="$DEST",type=bind"

docker run --mount $MOUNT_ARG $DOCKER_IMAGE
